config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resource :users, only: [:new, :create, :show]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'assist', to: 'event_users#new'
  post 'assist', to: 'event_users#create'
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, foreign_key: :creator_id, class_name: 'User'
  has_many :attendee, foreign_key: :event_id, class_name: 'EventUser'

  scope :previous, -> { where('datetime < ?', DateTime.now) }
  scope :upcoming, -> { where('datetime > ?', DateTime.now) }
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :attendee, foreign_key: :user_id, class_name: 'User'
  belongs_to :attended_event, foreign_key: :event_id, class_name: 'Event'

  def search_user(user_id)
    User.find_by(id: user_id)
  end

  def search_event(event_id)
    Event.find_by(id: event_id)
  end

  def self.past
    where('datetime < ?', DateTime.now)
  end

  def self.future
    where('datetime > ?', DateTime.now)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id, class_name: 'Event'
  has_many :attended_event, foreign_key: :user_id, class_name: 'EventUser'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    return false if current_user.nil?

    true
  end

  def require_user
    return if logged_in?

    flash[:alert] = 'You must be logged in to perform that action'
    redirect_to login_path
  end
end

app/controllers/event_users_controller.rb
# rubocop : disable Lint/NonLocalExitFromIterator

class EventUsersController < ApplicationController
  before_action :require_user

  def new
    @eventusers = EventUser.new
  end

  def create
    @event = Event.find_by(id: params[:format].to_i)
    @eventuser = EventUser.new(event_id: @event.id, user_id: current_user.id)

    @event.attendee.each do |user|
      if current_user.id == user.user_id
        redirect_to event_path(@event), alert: 'You are already assisting this event!' and return
      end
    end

    if @eventuser.save
      flash[:notice] = "#{current_user.first_name} is assisting #{@event.description}!"
      redirect_to event_path(@event)
    else
      flash[:alert] = @eventuser.errors.full_messages
      redirect_to events_path
    end
  end
end

# rubocop : enable Lint/NonLocalExitFromIterator

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user, except: %i[index show]

  def index
    @past_events = Event.previous
    @upcoming_events = Event.upcoming
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:notice] = "#{@event.title} event has been created!"
      redirect_to events_path
    else
      flash.now[:alert] = @event.errors.full_messages
      redirect_to new_event_path
    end
  end

  def show
    if Event.find_by(id: params[:id].to_i).nil?
      redirect_to events_path
    else
      @event = Event.find(params[:id].to_i)
      @attendees_id = @event.attendee.all
    end
  end

  private

  def event_params
    params.require(:event).permit(:description, :datetime)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to events_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(id: (params[:session][:number_field]).to_i)

    if @user.nil?
      @user = User.find_by(first_name: (params[:session][:first_name]).downcase)
      redirect_to login_path, alert: 'There was something wrong with your login details' if @user.nil?
    end

    return if @user.nil?

    session[:user_id] = @user.id
    flash[:notice] = 'Logged in successfully'
    redirect_to users_path(@user)
  end

  def destroy
    session[:user_id] = nil
    flash.now[:alert] = 'Log out!'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  before_action :require_same_user, only: [:show]

  def new
    @user = User.new
    redirect_to users_path if logged_in?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.first_name} to the Private Events app"
      redirect_to users_path
    else
      flash[:alert] = user.errors.full_messages
      redirect_to 'new'
    end
  end

  def show
    @created_events = current_user.events
    @past_events = current_user.attended_event.past
    @upcoming_events = current_user.attended_event.future
  end

  private

  def set_user
    if logged_in?
      @user = User.find(session[:user_id])
    else
      redirect_to login_path
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

  def require_same_user
    return unless current_user != @user

    flash[:alert] = 'You can only see your own events'
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/index.html.erb
<h1>Index Events</h1>

<h2>Upcoming Events</h2>
<div class=" row">
  <% Event.upcoming.each do |event| %>
    <div class="col-sm-3 my-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title" >EVENT</h5>
     
          <% unless event.title.nil? %>
            <p class="card-title" ><%= event.title %></p>
            <p class="card-title" ><%= event.datetime %></p>

          <% else %>
            <p class="card-text"> <%= event.description %></p>
            <p class="card-title" ><%= event.datetime %></p>
          <% end %>
        </div>
        <div class="card-footer">
          <%= link_to "Show the event", event%>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h2>Past Events</h2>
<div class=" row">
  <% Event.previous.each do |event| %>
    <div class="col-sm-3 my-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title" >EVENT</h5>
          <% unless event.title.nil? %>
            <p class="card-title" ><%= event.title %></p>
            <p class="card-title" ><%= event.datetime %></p>
          <% else %>
            <p class="card-text"> <%= event.description %></p>
            <p class="card-title" ><%= event.datetime %></p>
          <% end %>
        </div>
        <div class="card-footer">
          <%= link_to "Show the event", event%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<%= form_with model: @event, method: :post do |form| %>
  
  <ul class="mt-5 form-group">
    <label><h2>Description of your new Event! </h2></label>
    <%= form.text_area :description, rows: 10, class: "form-control", cols: 100, placeholder: "Event description here" %>
  </ul>

  <ul class="mt-5 form-group">
    <label>Date</label>
    <%= form.date_field :datetime, class: "form-control", placeholder: "Event date here", :value => Time.now.strftime('%Y-%m-%d') %>
  </ul>
  
  <ul>
    <%= form.submit "Create an event", class: "btn btn-lg btn-primary" %>
  </ul>
  <br>
<% end %>

app/views/events/show.html.erb
<h1>Show Event</h1>

<div class="card text-center mt-5">
  <div class="card-header">
    Show Event
  </div>
  <div class="card-body">
    <h5 class="card-title">
    <% if !@event.title.nil? %>
      <%= @event.title %>
    <% else %>
      Event
    <% end%>
    </h5>
    <p class="card-text">
       <%= @event.description %>
    </p>
    <p class="card-text">
       <small>-by <%= @event.user.first_name %> </small>
    </p>
     <%= link_to "Go Back", events_path ,  class: "btn btn-info" %>
     <% if logged_in? %>
      <%= link_to "Assist this event", assist_path(@event) ,  class: "btn btn-warning",  method: :post %>
     <% end %>
  </div>
  <div class="card-footer text-muted">
    <%= @event.datetime %>
  </div>
</div>

<h3 class="mt-5 mb-5 text-center">Attendees</h3>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
  <% @attendees_id.each do |user| %>
    <tr>
      <th scope="row"><%= user.id %></th>
      <td><%= user.search_user(user.user_id).first_name %></td>
      <td><%= user.search_user(user.user_id).last_name %></td>
      <td><%= user.search_user(user.user_id).email %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>

      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Private Events", root_path,  class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if logged_in? %>
          <li class="nav-item <%= 'active' if request.path ==  users_path(current_user) %>" >
              <%= link_to "Your profile", users_path(current_user),  class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if request.path ==  new_event_path %>">
              <%= link_to "Create an event", new_event_path,  class: "nav-link" %>
          </li>
        <% end %>
          <li class="nav-item <%= 'active' if request.path ==  events_path %>">
            <%= link_to "All Events", events_path,  class: "nav-link" %>
          </li>
      </ul>
      <div class="form-inline my-2 my-lg-0">
      <% if logged_in? %>
          <%= link_to "Log out", logout_path,  class: "btn btn-danger my-2 my-sm-0 ", method: :delete %>  
      <% else %>
          <%= link_to "Log in", login_path,  class: "btn btn-primary my-2 my-sm-0 ml-4" %>
          <%= link_to "Sign up", new_users_path,  class: "btn btn-primary my-2 my-sm-0 ml-4" %>
      <% end %>
      </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron mt-5">
  <h1 class="display-4">Home Page</h1>
  <p class="lead">Welcome to the Private Events rails app, the Microverse Associations project for Ruby on Rails module that consists of creating an application named 
  Private Events and that behaves similar to Eventbrite, which allows users to create events and then manage user signups. </p>
  <hr class="my-4">
  <p>
  Users can create events and send invitations and parties (sound familiar?). 
  Events take place at a specific date and at a location. A user can create events. 
  A user can attend many events. An event can be attended by many users. 
  The main goal is to put in practice the main concepts of Associations in rails.</p>
   <div class="form-inline my-2 my-lg-0">
      <% if logged_in? %>
          <%= link_to "Log out", logout_path,  class: "btn btn-lg btn-danger my-2 my-sm-0 ", method: :delete %>  
      <% else %>
          <%= link_to "Click here to log in", login_path,  class: "btn btn-lg btn-primary my-2 my-sm-0 ml-4" %>
          <%= link_to "Click here to sign up", new_users_path,  class: "btn btn-lg btn-primary my-2 my-sm-0 ml-4" %>
      <% end %>
      </div>
</div>

app/views/users/new.html.erb
<h1>Welcome to the Registration Page of Private Events app</h1>

<div class="center_div">

  <%= form_with model: @user, method: :post do |form| %>
    
    <div class="form-group mt-5">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: "form-control", placeholder: "Your first name here"%>
    </div>
    <div class="form-group">
      <%= form.submit "Create new user", class: "btn btn-lg btn-primary"  %>
    </div>
    <br>
  <% end %>

</div>

app/views/users/show.html.erb
<h1>Hello <%= @user.first_name.titlecase %> to show page</h1>

<h2 class="my-5">Events <%= @user.first_name.titlecase %> has created</h2>

<div class="card-group row">
  <% @created_events.each do |event| %>
  <div class="col-sm-3 my-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title" >MY EVENT</h5>

        <% unless event.title.nil? %>
          <p class="card-title" ><%= event.title %></p>
          <p class="card-title" ><%= event.datetime %></p>
        <% else %>
          <p class="card-text"> <%= event.description %></p>
          <p class="card-text"> <%= event.datetime %></p>
        <% end %>
      </div>
      <div class="card-footer">
          <%= link_to "Show the event", event %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<h2 class="my-5">Upcoming events</h2>

<div class="card-group row">
  <% @user.attended_event.each do |event| %>
    <% unless event.search_event(event.event_id).datetime.nil? %>
      <% if event.search_event(event.event_id).datetime > DateTime.now %>
        <div class="col-sm-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title" >MY EVENT</h5>

              <% unless event.search_event(event.event_id).title.nil? %>
                <p class="card-title" ><%= event.search_event(event.event_id).title %></p>
                <p class="card-title" ><%= event.search_event(event.event_id).datetime %></p>
              <% else %>
                <p class="card-text"><%= event.search_event(event.event_id).description %></p>
                <p class="card-text"><%= event.search_event(event.event_id).datetime %></p>
              <% end %>
            </div>
            <div class="card-footer">
                <%= link_to "Show the event", event.search_event(event.event_id) %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>


<h2 class="my-5">Previously attended events</h2>

<div class="card-group row">
  <% @user.attended_event.each do |event| %>
    <% unless event.search_event(event.event_id).datetime.nil? %>
      <% if event.search_event(event.event_id).datetime <= DateTime.now %>
        <div class="col-sm-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title" >MY EVENT</h5>

              <% unless event.search_event(event.event_id).title.nil? %>
                <p class="card-title" ><%= event.search_event(event.event_id).title %></p>
                <p class="card-title" ><%= event.search_event(event.event_id).datetime %></p>
              <% else %>
                <p class="card-text"><%= event.search_event(event.event_id).description %></p>
                <p class="card-text" ><%= event.search_event(event.event_id).datetime %></p>
              <% end %>
            </div>
            <div class="card-footer">
                <%= link_to "Show the event", event.search_event(event.event_id) %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>